branches:
  except:
    - gh-pages
image: Visual Studio 2017
environment:
  nodejs_version: "LTS"
init:
- tzutil /s "Central Standard Time"
- cmd: node -v
- cmd: npm -v
- ps: $PSVersionTable
install:
  - npm install
platform:
  - Win32
configuration:
  - Debug
build: off
test_script:
  - npm run lint
after_test:
  - npm run build
artifacts:
  - path: 'dist\*.nipkg'
    name: 'nipackage'
    type: File
