branches:
  except:
    - gh-pages
image: Visual Studio 2017
environment:
  nodejs_version: "LTS"
init:
- tzutil /s "Central Standard Time"
- cmd: node -v
- cmd: npm -v
- ps: $PSVersionTable
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - mkdir DownloadCache
  - curl -fsS -o .\DownloadCache\NIPackageManager17.5.exe http://ftp.ni.com/support/softlib/AST/NIPM/NIPackageManager17.5.exe
  - start /WAIT .\DownloadCache\NIPackageManager17.5.exe /Q
platform:
  - Win32
configuration:
  - Debug
build: off
test_script:
  - npm run lint
after_test:
  - npm run build
artifacts:
  - path: 'dist\*.nipkg'
    name: 'nipackage'
    type: File
